---
- name: show version and other user level commands
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: run multiple commands on remote nodes
      ansible.netcommon.network_cli:
        commands:
          - show version
          - show ip int brief

      register: print_output1

    - debug: var=print_output1.stdout_lines
